set shell=bash

" Polyglot
" Needs to be declared before loading vim-polyglot
" https://github.com/sheerun/vim-polyglot#troubleshooting
let g:polyglot_disabled=['go', 'terraform']

" ~~~~ Start Plug config ~~~~
call plug#begin('~/.vim/plugged')

Plug 'bling/vim-airline'
Plug 'bronson/vim-visual-star-search'
Plug 'croaker/mustang-vim'
Plug 'fatih/vim-go', { 'do': 'nvim -c GoUpdateBinaries -c qa!' }
Plug 'hashivim/vim-terraform'
Plug 'honza/vim-snippets'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-nvim-lsp-signature-help'
Plug 'hrsh7th/cmp-path'
Plug 'hrsh7th/cmp-cmdline'
Plug 'hrsh7th/nvim-cmp'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && ~/.nodenv/shims/npx --yes yarn install' }
Plug 'jlanzarotta/bufexplorer'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'mhinz/vim-signify'
Plug 'neovim/nvim-lspconfig'
Plug 'onsails/lspkind.nvim'
Plug 'quangnguyen30192/cmp-nvim-ultisnips'
Plug 'scrooloose/nerdtree'
Plug 'SirVer/ultisnips'
Plug 'sheerun/vim-polyglot'
Plug 'tomtom/tcomment_vim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'vim-scripts/InsertChar'
Plug 'vim-utils/vim-husk'

call plug#end()

" ~~~~ End Plug config ~~~~

set nocompatible

" Mustang colorscheme
set background=dark
if !empty(globpath(&rtp, 'colors/mustang.vim'))
  colorscheme mustang
  hi VertSplit ctermfg=242 ctermbg=none
  hi FloatBorder guibg=none ctermbg=none
  hi NormalFloat guibg=none ctermbg=none
endif

" View options
set nowrap
set nu
set showcmd
set title

" Consistency
nmap Y y$
vmap y ygv<ESC>
nmap p p`]

" Visual move
vmap K :m '<-2<CR>gv=gv
vmap J :m '>+1<CR>gv=gv

" Enable mouse
set mouse=a

" Use system clipboard
set clipboard=unnamed

" Sudo write
cmap w!! w !sudo -S tee > /dev/null %

" Cursor styles for Insert/Replace/Normal modes
let &t_SI="\e[6 q"
let &t_SR="\e[4 q"
let &t_EI="\e[2 q"

" Highlight row and column
set cursorline
set cursorcolumn
hi CursorLine cterm=NONE

" Only display cursorline on active pane
" From: http://stackoverflow.com/questions/12017331/how-can-i-make-vim-highlight-the-current-line-on-only-the-active-buffer
augroup CursorLine
  au!
  au VimEnter,WinEnter,BufWinEnter * setlocal cursorline cursorcolumn
  au WinLeave * setlocal nocursorline nocursorcolumn
augroup END

" Tab options
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

" Indent shortcuts
vmap > >gv
vmap < <gv
nmap > >>
nmap < <<

" Search options
set hlsearch
set ignorecase
set smartcase

" Set leader to Space
let mapleader="\<space>"

" Open new buffers helpers
nmap <leader>sh :leftabove vnew<cr>
nmap <leader>sl :rightbelow vnew<cr>
nmap <leader>sk :leftabove new<cr>
nmap <leader>sj :rightbelow new<cr>
nmap <leader>st :tabnew<CR>

" Edit file helpers
nmap <leader>ew :e <C-R>=expand('%:h').'/'<cr>
nmap <leader>es :sp <C-R>=expand('%:h').'/'<cr>
nmap <leader>ev :vsp <C-R>=expand('%:h').'/'<cr>
nmap <leader>et :tabe <C-R>=expand('%:h').'/'<cr>

" Tab helpers
nmap <leader>tn :tabnew<CR>
nmap <leader>tl gt
nmap <leader>th gT

" Highlight trailiing whitespace
match ErrorMsg '\s\+$'
nmap <leader>rtw :%s/\s\+$//e<CR>``

" Insert current directory path into a command
cnoremap <expr> <C-P> getcmdline()[getcmdpos()-2] ==# ' ' ? expand('%:p:h').'/' : "\<C-P>"

" Find merge conflict markers
nmap <silent> <leader>fc <ESC>/\v^[<=>\|]{7}( .*\|$)<CR>

" Set Python virtualenv
let g:python3_host_prog='~/.pyenv/versions/neovim/bin/python'

" Disable unused providers
let g:loaded_ruby_provider=0
let g:loaded_node_provider=0
let g:loaded_perl_provider=0

" Set shell to fish
set shell=fish

" Insert single character
nmap <C-I> :<C-U>call InsertChar#insert(v:count1)<CR>

" FZF
nmap <C-P> :Files<CR>

" BufExplorer
function! BufExplorerVToggle()
  let winnr = bufwinnr('\[BufExplorer]')

  if winnr == -1
    execute 'BufExplorerVerticalSplit'
    execute 'vertical resize 31'
  else
    execute winnr . 'wincmd c'
  endif
endfunction

command! BufExplorerVToggle :call BufExplorerVToggle()
let g:bufExplorerDisableDefaultKeyMapping=1
nmap <leader>b :BufExplorerVToggle<CR>

" NERDTree
nmap <leader>n :NERDTreeToggle<CR>
let NERDTreeHighlightCursorline=1
let g:NERDTreeQuitOnOpen=1

" tComment
let g:tcomment_mapleader1=''
let g:tcomment_opleader1=''
let g:tcomment_opleader2=''
nmap <C-_> :TComment<CR>
vmap <C-_> :TCommentMaybeInline<CR>gv<ESC>
imap <C-_> <C-O>:TComment<CR>

" Go
let g:go_fmt_command="goimports"

" Terraform
let g:terraform_fmt_on_save=1

" Markdown
au BufRead,BufNewFile *.md setlocal textwidth=80
let g:mkdp_auto_start=1

" UltiSnips
let g:UltiSnipsExpandTrigger='<Plug>(ultisnips_expand)'
let g:UltiSnipsJumpForwardTrigger='<Plug>(ultisnips_jump_forward)'
let g:UltiSnipsJumpBackwardTrigger='<Plug>(ultisnips_jump_backward)'
let g:UltiSnipsListSnippets='<C-X><C-S>'
let g:UltiSnipsRemoveSelectModeMappings=0

" nvim-cmp
if has('nvim') && isdirectory(g:plugs['nvim-lspconfig'].dir)
lua <<EOF
  local t = function(str)
      return vim.api.nvim_replace_termcodes(str, true, true, true)
  end

  local cmp = require('cmp')
  local lspkind = require('lspkind')

  cmp.setup({
    formatting = {
      format = lspkind.cmp_format({
        preset = "codicons",
        mode = "symbol_text",
        menu = ({
          buffer = "[Buffer]",
          path = "[Path]",
          nvim_lsp = "[LSP]",
          ultisnips = "[Snip]",
        }),
      }),
    },
    view = {
      entries = {
        name = "custom",
        selection_order = "near_cursor",
      },
    },
    snippet = {
      expand = function(args)
        vim.fn["UltiSnips#Anon"](args.body)
      end,
    },
    window = {
      completion = cmp.config.window.bordered(),
      documentation = cmp.config.window.bordered(),
    },
    mapping = {
      ["<Tab>"] = cmp.mapping({
        c = function()
          if cmp.visible() then
            cmp.select_next_item({ behavior = cmp.SelectBehavior.Insert })
          else
            cmp.complete()
          end
        end,
        i = function(fallback)
          if cmp.visible() then
            cmp.select_next_item({ behavior = cmp.SelectBehavior.Insert })
          elseif vim.fn["UltiSnips#CanJumpForwards"]() == 1 then
            vim.api.nvim_feedkeys(t("<Plug>(ultisnips_jump_forward)"), 'm', true)
          else
            fallback()
          end
        end,
        s = function(fallback)
          if vim.fn["UltiSnips#CanJumpForwards"]() == 1 then
            vim.api.nvim_feedkeys(t("<Plug>(ultisnips_jump_forward)"), 'm', true)
          else
            fallback()
          end
        end
      }),
      ["<S-Tab>"] = cmp.mapping({
        c = function()
          if cmp.visible() then
            cmp.select_prev_item({ behavior = cmp.SelectBehavior.Insert })
          else
            cmp.complete()
          end
        end,
        i = function(fallback)
          if cmp.visible() then
            cmp.select_prev_item({ behavior = cmp.SelectBehavior.Insert })
          elseif vim.fn["UltiSnips#CanJumpBackwards"]() == 1 then
            return vim.api.nvim_feedkeys( t("<Plug>(ultisnips_jump_backward)"), 'm', true)
          else
            fallback()
          end
        end,
        s = function(fallback)
          if vim.fn["UltiSnips#CanJumpBackwards"]() == 1 then
            return vim.api.nvim_feedkeys( t("<Plug>(ultisnips_jump_backward)"), 'm', true)
          else
            fallback()
          end
        end
      }),
      ['<Down>'] = cmp.mapping(cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }), {'i'}),
      ['<Up>'] = cmp.mapping(cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }), {'i'}),
      ['<C-n>'] = cmp.mapping({
        c = function()
          if cmp.visible() then
            cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })
          else
            vim.api.nvim_feedkeys(t('<Down>'), 'n', true)
          end
        end,
        i = function(fallback)
          if cmp.visible() then
            cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })
          else
            fallback()
          end
        end
      }),
      ['<C-p>'] = cmp.mapping({
        c = function()
          if cmp.visible() then
            cmp.select_prev_item({ behavior = cmp.SelectBehavior.Select })
          else
            vim.api.nvim_feedkeys(t('<Up>'), 'n', true)
          end
        end,
        i = function(fallback)
          if cmp.visible() then
            cmp.select_prev_item({ behavior = cmp.SelectBehavior.Select })
          else
            fallback()
          end
        end
      }),
      ['<C-b>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), {'i', 'c'}),
      ['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), {'i', 'c'}),
      ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), {'i', 'c'}),
      ['<C-e>'] = cmp.mapping({ i = cmp.mapping.close(), c = cmp.mapping.close() }),
      ['<CR>'] = cmp.mapping({
        i = cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Replace, select = false }),
      }),
    },
    sources = cmp.config.sources({
      { name = 'nvim_lsp' },
      { name = 'ultisnips' },
    }, {
      { name = 'nvim_lsp_signature_help' },
    }, {
      { name = 'path' },
      { name = 'buffer' },
    })
  })

  cmp.setup.cmdline({ '/', '?' }, {
    mapping = cmp.mapping.preset.cmdline(),
    sources = {
      { name = 'buffer' }
    }
  })

  cmp.setup.cmdline(':', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = cmp.config.sources({
      { name = 'path' }
    }, {
      { name = 'cmdline' }
    })
  })

  local capabilities = require('cmp_nvim_lsp').default_capabilities()
  local lspconfig = require('lspconfig')

  local lsps = {
    'gopls',
    'pyright',
    'terraformls',
    'tsserver',
  }

  for _, lsp in ipairs(lsps) do
    lspconfig[lsp].setup {
      capabilities = capabilities
    }
  end

  vim.lsp.handlers['textDocument/hover'] = vim.lsp.with(
    vim.lsp.handlers.hover,
    {
      focusable = false,
      border = 'rounded',
      style = "minimal",
      max_width = 80,
      silent = true,
    }
  )
  vim.lsp.handlers['textDocument/signatureHelp'] = vim.lsp.with(
    vim.lsp.handlers.signature_help, {
      border = 'rounded',
      close_events = {"BufHidden", "InsertLeave"},
    }
  )
  vim.diagnostic.config {
    float = {
      border = "rounded",
    }
  }

  vim.o.updatetime = 1000
  vim.api.nvim_create_autocmd({ "CursorHold", "CursorHoldI" }, {
    group = vim.api.nvim_create_augroup("float_diagnostic", { clear = true }),
    callback = function ()
      vim.diagnostic.open_float(nil, {focus=false})
      vim.lsp.buf.hover()
    end
  })

  vim.lsp.set_log_level('off')
EOF
endif
